import streamlit as st

from components.hero import hero
from components.cards import workspace_card


def show_home():

    # -------------------------------------------------
    # HERO
    # -------------------------------------------------

    hero()

    st.markdown("<br><br>", unsafe_allow_html=True)

    # -------------------------------------------------
    # WORKSPACE TITLE
    # -------------------------------------------------

    st.markdown(
        """
        <div style="text-align:center;margin-bottom:50px;">

            <h2 style="
                font-family:var(--font-display);
                margin-bottom:10px;
            ">
                Choose Your Workspace
            </h2>

            <p style="
                color:var(--text-secondary);
                max-width:650px;
                margin:auto;
                line-height:1.8;
            ">
                Select one of AthenaVision's intelligent modules
                to begin analyzing classrooms, libraries and
                collaborative learning spaces.
            </p>

        </div>
        """,
        unsafe_allow_html=True,
    )

    # -------------------------------------------------
    # ROW 1
    # -------------------------------------------------

    col1, col2 = st.columns(2, gap="large")

    with col1:

        workspace_card(
            "👁",
            "Visual Analysis",
            "Analyze uploaded classroom and library images using AI-powered people detection.",
            "vision",
            "📷 Visual Analysis",
        )

    with col2:

        workspace_card(
            "🎥",
            "Live Monitoring",
            "Monitor occupancy in real time using your webcam and intelligent computer vision.",
            "monitor",
            "📹 Live Monitoring",
        )

    st.markdown("<br>", unsafe_allow_html=True)

    # -------------------------------------------------
    # ROW 2
    # -------------------------------------------------

    col3, col4 = st.columns(2, gap="large")

    with col3:

        workspace_card(
            "📊",
            "Insights",
            "Explore occupancy statistics, trends and analytical summaries generated by AthenaVision.",
            "insights",
            "📊 Insights",
        )

    with col4:

        workspace_card(
            "🕒",
            "Activity History",
            "Review previous AI analyses, monitoring sessions and generated activity logs.",
            "history",
            "🕒 Activity History",
        )

    st.markdown("<br>", unsafe_allow_html=True)

    # -------------------------------------------------
    # ROW 3
    # -------------------------------------------------

    col_left, col_center, col_right = st.columns([1, 2, 1])

    with col_center:

        workspace_card(
            "🎬",
            "Video Intelligence",
            "Analyze recorded classroom videos to extract intelligent occupancy information.",
            "video",
            "🎥 Video Intelligence",
        )

    st.markdown("<br><br><br>", unsafe_allow_html=True)